const types = {
  CHANGE_NICKNAME: 'CHANGE_NICKNAME',
  SEND_MESSAGE: 'SEND_MESSAGE',

  FETCH_ROOMS_REQUEST: 'FETCH_ROOMS_REQUEST',
  FETCH_ROOMS_FAILURE: 'FETCH_ROOMS_FAILURE',
  FETCH_ROOMS_SUCCESS: 'FETCH_ROOMS_SUCCESS',
  
  FETCH_MESSAGES_REQUEST: 'FETCH_MESSAGES_REQUEST',
  FETCH_MESSAGES_FAILURE: 'FETCH_MESSAGES_FAILURE',
  FETCH_MESSAGES_SUCCESS: 'FETCH_MESSAGES_SUCCESS',

  CHANGE_ROOM: 'CHANGE_ROOM',
}

export default types;
